FROM golang:1.14-alpine AS build

WORKDIR /src/
COPY main.go collector.go go.* /src/

ENV GO111MODULE="on"
ENV CGO_ENABLED="0"

RUN go mod vendor && go build -mod vendor -o /bin/tfe-prometheus-exporter

FROM alpine
COPY --from=build /bin/tfe-prometheus-exporter /bin/tfe-prometheus-exporter
ENTRYPOINT ["/bin/tfe-prometheus-exporter"]